# Default config for the entire script (rename to config.yaml)
# Dataset and model arguments
dataset_lang: as
dataset_name: mozilla-foundation/common_voice_11_0
dataset_cache: ./datasets
model_lang: assamese
model_name: whisper-medium
model_cache: ./models
gpu_device: null
whisper_pretrained: null
checkpoint_name: null
checkpoint_dir: null
training_max_steps: 4000
hf_token: null

# Training arguments
per_device_train_batch_size: 16
gradient_accumulation_steps: 1
learning_rate: 1e-5
warmup_steps: 500
max_steps: 4000
gradient_checkpointing: true
fp16: true
eval_strategy: steps
per_device_eval_batch_size: 8
predict_with_generate: true
generation_max_length: 225
save_steps: 1000
eval_steps: 1000
logging_steps: 25
report_to:
  - tensorboard
load_best_model_at_end: true
metric_for_best_model: wer
greater_is_better: false
push_to_hub: true
