[project]
name = "whisper-finetune"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openai-whisper",
]

[tool.uv.sources]
openai-whisper = { git = "https://github.com/openai/whisper.git" }
